# Generated by Django 3.1.3 on 2025-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alloted_teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher_email', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('stz', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paper_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=15, null=True)),
                ('stz', models.CharField(max_length=100)),
                ('paper', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=1000)),
                ('org_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='superintendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('work_exp', models.CharField(max_length=1000)),
                ('work_address', models.CharField(max_length=100)),
            ],
        ),
    ]
